FROM almalinux:9

RUN dnf -y update && \
    dnf -y install \
        systemd \
        systemd-sysv \
        openssh-clients \
        bash-completion \
        iproute \
        openssh-server \
        sshpass \
        git \
        vim \
        less \
        procps-ng \
        which \
        python3 \
        python3-pip \
        sudo \
        rsync \
        tar \
        gzip \
        unzip && \
    dnf clean all

RUN echo 'root:ansible' | chpasswd
RUN ssh-keygen -A

CMD ["/sbin/init"]
