FROM almalinux:9

RUN dnf -y update && \
    dnf -y install \
        openssh-clients \
        bash-completion \
        iproute \
        openssh-server \
        git \
        vim \
        less \
        procps-ng \
        which \
        python3 \
        python3-pip \
        sudo \
        rsync \
        tar \
        gzip \
        unzip && \
    dnf clean all

RUN echo 'root:ansible' | chpasswd
RUN ssh-keygen -A

CMD ["/usr/sbin/sshd", "-D", "-e"]
