---
version: "3.7"

services:
  ansible:
    build:
      context: .
    networks:
      vm_net:
        ipv4_address: 192.0.2.2
    volumes:
      - ../:/ansible-exercise
  host000:
    build:
      context: .
      dockerfile: Dockerfile_vm
      target: main
    privileged: yes
    networks:
      vm_net:
        ipv4_address: 192.0.2.100
  host001:
    build:
      context: .
      dockerfile: Dockerfile_vm
      target: main
    privileged: yes
    networks:
      vm_net:
        ipv4_address: 192.0.2.101
  host002:
    build:
      context: .
      dockerfile: Dockerfile_vm
      target: main
    privileged: yes
    networks:
      vm_net:
        ipv4_address: 192.0.2.102
  db1:
    build:
      context: .
      dockerfile: Dockerfile_vm
      target: main
    privileged: yes
    expose:
      - "3306"
    networks:
      vm_net:
        ipv4_address: 192.0.2.10
  rp1:
    build:
      context: .
      dockerfile: Dockerfile_vm
      target: main
    privileged: yes
    expose:
      - "8443"
    ports:
      - "8443:8443"
    networks:
      vm_net:
        ipv4_address: 192.0.2.11
  app1:
    build:
      context: .
      dockerfile: Dockerfile_vm
      target: main
    privileged: yes
    expose:
      - "80"
      - "8080"
    ports:
      - "18080:8080"
    networks:
      vm_net:
        ipv4_address: 192.0.2.12
  app2:
    build:
      context: .
      dockerfile: Dockerfile_vm
      target: main
    privileged: yes
    expose:
      - "80"
      - "8080"
    networks:
      vm_net:
        ipv4_address: 192.0.2.13

networks:
  vm_net:
    ipam:
      driver: default
      config:
        - subnet: 192.0.2.0/24
