# base image
# ---------------------------------------------------------
FROM centos:7 as base

WORKDIR /root/.ssh

RUN set -ex \
    && yum install -y openssh-server sudo \
    && rm -rf /var/cache/yum/* \
    && yum clean all \
    && sed -i -e 's/#UseDNS/UseDNS/g' /etc/ssh/sshd_config \
    && systemctl restart sshd.server \
    && systemctl enable sshd.service \

COPY ssh/id_ecdsa.pub ./authorized_keys

RUN chmod 600 authorized_keys

# main image
# ---------------------------------------------------------
FROM base as main

EXPOSE 22

CMD [ "/usr/sbin/init" ]

# develop image
# ---------------------------------------------------------
FROM base as dev

RUN yum install -y iproute traceroute telnet tcpdump bind-utils

EXPOSE 22

CMD [ "/usr/sbin/init" ]